### PR TITLE
Feat/home & wishlist pages

### PR DESCRIPTION
**Pull request by tonymike99**
Hi team,
I've added the home page and wishlist page.

https://deploy-preview-5--candelify-react.netlify.app/
https://deploy-preview-5--candelify-react.netlify.app/wishlist

### CODE REVIEW

**Review by rutu14 — APPROVED** [review]
The code is good to merge.
UI Suggestion: When cursor is on button, you can turn it to pointer.
UI Appreciation: The gradient on hover of the icons are amazing.

**Review by Shubhamkr2610 — APPROVED** [review]
code looks clean to me . You are good to go

**Review by Shubhamkr2610 — APPROVED** [review]

**Review by Shubhamkr2610 — APPROVED** [review]

**Comment by devAmlan** [comment]
Everything looks fine. The UI is good and the code looks clean. I think it's ready to merge.

**Review by devAmlan — APPROVED** [review]

**Review by sumitk-singh — APPROVED** [review]
codes look clean to me.
UI looks good, 
Good to go.

**Pull request merged**
